# Generated by Django 5.1.2 on 2024-11-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_account_position_alter_account_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
