# Generated by Django 5.1.2 on 2024-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, choices=[('dean', 'Dean'), ('head', 'Head')], default='dean', max_length=20, null=True),
        ),
    ]
