# Generated by Django 5.1.2 on 2025-01-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
