# Generated by Django 5.1.2 on 2025-01-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_order_status'),
        ('core', '0014_product_user'),
    ]

    operations = [
    ]
