# Generated by Django 5.1.2 on 2025-01-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
