# Generated by Django 5.1.2 on 2025-01-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_account_reset_token'),
        ('core', '0018_remove_product_price'),
    ]

    operations = [
    ]
