# Generated by Django 5.1.2 on 2026-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('dispatch', 'Dispatch')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('dispatch', 'Dispatch')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('dispatch', 'Dispatch')], default='pending', max_length=20),
        ),
    ]
